import json
import os
import shutil
from pathlib import Path

from app.config import settings

SETTINGS_FILE = Path("/var/lib/repo-manager/proxy.json")
PROXIES_FILE = Path("/var/lib/repo-manager/repo-proxies.json")
NGINX_PROXY_CONF = Path("/var/lib/repo-manager/repo-manager-proxies.conf")


def load_repo_proxies() -> list:
    if not PROXIES_FILE.exists():
        return []
    try:
        return json.loads(PROXIES_FILE.read_text())
    except (OSError, json.JSONDecodeError):
        return []


def save_repo_proxies(items: list) -> list:
    PROXIES_FILE.parent.mkdir(parents=True, exist_ok=True)
    PROXIES_FILE.write_text(json.dumps(items, ensure_ascii=False, indent=2))
    locations = ["# generated by repo-manager"]
    for item in items:
        name = item["name"]
        upstream = item["upstream"].rstrip("/") + "/"
        locations.append(f"location /repo/proxy/{name}/ {{")
        locations.append(f"    proxy_pass {upstream};")
        locations.append("    proxy_set_header Host $proxy_host;")
        locations.append("    proxy_ssl_server_name on;")
        locations.append("}")
    NGINX_PROXY_CONF.write_text("\n".join(locations) + "\n")
    return items


def load_proxy() -> dict:
    data = {"proxy_url": settings.PROXY_URL or "", "no_proxy": settings.NO_PROXY or "127.0.0.1,localhost"}
    if SETTINGS_FILE.exists():
        try:
            saved = json.loads(SETTINGS_FILE.read_text())
            data.update({k: saved.get(k, data[k]) for k in data})
        except (OSError, json.JSONDecodeError):
            pass
    return data


def save_proxy(proxy_url: str, no_proxy: str) -> dict:
    data = {}
    if SETTINGS_FILE.exists():
        try:
            data = json.loads(SETTINGS_FILE.read_text())
        except (OSError, json.JSONDecodeError):
            data = {}
    data["proxy_url"] = proxy_url.strip()
    data["no_proxy"] = no_proxy.strip() or "127.0.0.1,localhost"
    SETTINGS_FILE.parent.mkdir(parents=True, exist_ok=True)
    SETTINGS_FILE.write_text(json.dumps(data))
    return {"proxy_url": data["proxy_url"], "no_proxy": data["no_proxy"]}


def proxy_env() -> dict:
    env = os.environ.copy()
    data = load_proxy()
    proxy = data.get("proxy_url") or ""
    if proxy:
        env["http_proxy"] = proxy
        env["https_proxy"] = proxy
        env["HTTP_PROXY"] = proxy
        env["HTTPS_PROXY"] = proxy
    else:
        for key in ("http_proxy", "https_proxy", "HTTP_PROXY", "HTTPS_PROXY"):
            env.pop(key, None)
    env["no_proxy"] = data.get("no_proxy") or "127.0.0.1,localhost"
    env["NO_PROXY"] = env["no_proxy"]
    return env


def load_min_free_gb() -> str:
    data = {}
    if SETTINGS_FILE.exists():
        try:
            data = json.loads(SETTINGS_FILE.read_text())
        except (OSError, json.JSONDecodeError):
            data = {}
    return str(data.get("min_free_gb") or "")


def save_min_free_gb(value: str) -> str:
    data = {}
    if SETTINGS_FILE.exists():
        try:
            data = json.loads(SETTINGS_FILE.read_text())
        except (OSError, json.JSONDecodeError):
            data = {}
    data["min_free_gb"] = value.strip()
    SETTINGS_FILE.parent.mkdir(parents=True, exist_ok=True)
    SETTINGS_FILE.write_text(json.dumps(data))
    return data["min_free_gb"]


def free_gb() -> float:
    path = Path("/var/lib/repo-manager")
    path.mkdir(parents=True, exist_ok=True)
    return shutil.disk_usage(path).free / 1024 / 1024 / 1024


def sync_blocked() -> str:
    raw = load_min_free_gb()
    if not raw:
        return ""
    try:
        limit = float(raw.replace(",", "."))
    except ValueError:
        return ""
    free = free_gb()
    if free < limit:
        return f"Свободно {free:.1f} ГБ, порог {limit:.0f} ГБ. Sync не запущен."
    return ""
